Sorular: 

# https://github.com/EmincanY


1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin
2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.
3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)
4) 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.
5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.
6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)
7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)
8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)
9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)
10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.
11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.
12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.
13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.
14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.
15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [1]:
# Q-1 
# Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin
import numpy as np
array_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("Dimension", array_3d.ndim)

Dimension 3


In [2]:
# Q-2
# 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.
array_1d = np.arange(34,113,6)
print("1D Array", array_1d)

1D Array [ 34  40  46  52  58  64  70  76  82  88  94 100 106 112]


In [3]:
# Q-3
# 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun) 
linear_array = np.linspace(50,500,91,dtype=int)
print("Linear Array", linear_array)


Linear Array [ 50  55  60  65  70  75  80  85  90  95 100 105 110 115 120 125 130 135
 140 145 150 155 160 165 170 175 180 185 190 195 200 205 210 215 220 225
 230 235 240 245 250 255 260 265 270 275 280 285 290 295 300 305 310 315
 320 325 330 335 340 345 350 355 360 365 370 375 380 385 390 395 400 405
 410 415 420 425 430 435 440 445 450 455 460 465 470 475 480 485 490 495
 500]


In [4]:
# Q-4
# 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.
log_array = np.logspace(2,5,8)
print("Log Array", log_array)


Log Array [   100.            268.26957953    719.685673     1930.69772888
   5179.47467923  13894.95494373  37275.93720315 100000.        ]


In [6]:
# Q-5
# 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.

matrix = np.arange(9).reshape(3,3)
print("Matrix \n", matrix)


Matrix 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# Q-6
# 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)
zero_matrix = np.zeros((6,6),dtype=int)
print("Zero Matrix \n", zero_matrix)

Zero Matrix 
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [8]:
# Q-7
# 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)
one_matrix = np.ones((4,4),dtype=int)
print("One Matrix \n", one_matrix)

One Matrix 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [9]:
# Q-8
# 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

identity_matrix = np.eye(8,dtype=int)
print("Identity Matrix \n", identity_matrix)

Identity Matrix 
 [[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [10]:
# Q-9
# 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) 
# (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)

diagonal_matrix = np.eye(5,5,k=0,dtype=int)*3
print("Diagonal Matrix \n", diagonal_matrix)

Diagonal Matrix 
 [[3 0 0 0 0]
 [0 3 0 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]]


In [11]:
# Q-10
# np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

random_array = np.random.rand(6)
print("Random Array", random_array)

Random Array [0.32092347 0.33847097 0.66274738 0.5652764  0.3099164  0.78734159]


In [13]:
# Q-11
# np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun.
# Ardından bu arrayin shape'ini kontrol edin.

random_array_2 = np.random.randint(50,101,(5,2))
print("Random Array 2 \n", random_array_2)
print("Shape of Random Array 2", random_array_2.shape)


Random Array 2 
 [[85 82]
 [67 68]
 [68 58]
 [73 71]
 [53 77]]
Shape of Random Array 2 (5, 2)


In [14]:
# Q-12
# np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki 
# tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

random_array_3 = np.random.randint(100,1000,(2,5,5))
print("Random Array 3 \n", random_array_3)
print("Dimension of Random Array 3", random_array_3.ndim)

Random Array 3 
 [[[488 825 427 883 215]
  [268 995 460 167 308]
  [328 445 295 823 698]
  [499 690 538 597 461]
  [607 990 846 912 903]]

 [[805 839 419 751 734]
  [371 674 571 787 266]
  [953 704 831 369 271]
  [814 940 478 338 480]
  [844 320 362 138 474]]]
Dimension of Random Array 3 3


In [16]:
# Q-13
# np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. 
# Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

random_array_4 = np.random.randint(0,101,10)
print("Random Array 4:", random_array_4)
max_value = random_array_4.max()
min_value = random_array_4.min()
max_index = random_array_4.argmax()
min_index = random_array_4.argmin()
print("Max Value", max_value)
print("Min Value", min_value)
print("Max Index", max_index)
print("Min Index", min_index)

Random Array 4: [ 7 47 15 79 80 20 67 66 31 16]
Max Value 80
Min Value 7
Max Index 4
Min Index 0


In [19]:
# Q-14
# np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. 
# Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

random_array_5 = np.random.randint(300,501,(2,2,5)) 
print("Random Array 5 \n", random_array_5)

for i in range(2):
    for j in range(2):
        for k in range(5):
            if random_array_5[i][j][k] == random_array_5.max():
                print("Max Value", random_array_5.max())
                print("Max Index", i,j,k)
            if random_array_5[i][j][k] == random_array_5.min():
                print("Min Value", random_array_5.min())
                print("Min Index", i,j,k)
        



Random Array 5 
 [[[360 399 333 332 435]
  [394 371 352 442 352]]

 [[492 400 433 465 325]
  [318 338 409 348 423]]]
Max Value 492
Max Index 1 0 0
Min Value 318
Min Index 1 1 0


In [21]:
# Q-15
# 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. 
# Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

int_array = np.arange(51) 
int_array[20:36] = 500
print("Integer Array \n", int_array)
print("Broadcasting is done \n", int_array[20:36])


Integer Array 
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50]
Broadcasting is done 
 [500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500]
