# Hatırlatmalar

In [11]:
import numpy as np

In [12]:
np.array([[1,2,3,4] , [5,6,7,8] , [10,20,30,40]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40]])

In [13]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
np.linspace(10,100,6)

array([ 10.,  28.,  46.,  64.,  82., 100.])

In [ ]:
np.logspace(1,3, 20 )

array([  10.        ,   12.74274986,   16.23776739,   20.69138081,
         26.36650899,   33.59818286,   42.81332399,   54.55594781,
         69.51927962,   88.58667904,  112.88378917,  143.84498883,
        183.29807108,  233.57214691,  297.63514416,  379.26901907,
        483.29302386,  615.84821107,  784.75997035, 1000.        ])

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((3,4) , dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
np.eye(3 , dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [22]:
np.identity(3 , dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [25]:
np.random.rand(3)

array([0.84086621, 0.47648258, 0.27192055])

In [28]:
np.random.rand(6)

array([0.34194699, 0.99843491, 0.59517062, 0.09526653, 0.45393759,
       0.70238821])

In [30]:
np.random.randint(10,20)

12

In [31]:
np.random.randint(10,20 , 3)

array([17, 19, 15])

In [33]:
arr2d = np.array([[1,2,3] , [4,5,6] , [10,20,30]])
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [34]:
arr2d.ndim

2

In [35]:
arr2d.shape

(3, 3)

In [37]:
arr2d[0][-1]

3

In [38]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [39]:
arr2d.max()

30

In [40]:
arr2d.argmax()

8

In [42]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[2:6] = 500

In [46]:
arr

array([  0,   1, 500, 500, 500, 500,   6,   7,   8,   9])

In [47]:
arr.dtype

dtype('int64')

In [49]:
arr = arr.astype('float')

In [50]:
arr

array([  0.,   1., 500., 500., 500., 500.,   6.,   7.,   8.,   9.])

# Bir Arrayin Shape'ini kontrol etmek

In [51]:
# Bir array'in shapeini kontrol etmek için .shape attribute'u kullanılır.
# Bir arrayin shape'i her boyuttaki öğelerinin sayısına eşittir

In [52]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [53]:
arr2d.shape

(3, 3)

In [55]:
arr3d = np.array([[ [1,2,3] ,[4,5,6] , [10,25,35] ,[40,50,60]] , [[10,20,30] , [5,10,20] ,[11,22,33] ,[44,55,66] ]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 25, 35],
        [40, 50, 60]],

       [[10, 20, 30],
        [ 5, 10, 20],
        [11, 22, 33],
        [44, 55, 66]]])

In [56]:
arr3d.ndim

3

In [57]:
arr3d.shape

(2, 4, 3)

# Bir Array'i Reshape(Yeniden Şekillendirme) Etme

In [58]:
# .reshape() metodu arrayin şeklini değiştirmeye yarar.
# .reshape() yaparken toplam eleman sayısını sabit tutmaya dikkat edilmeli.

In [59]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 25, 35],
        [40, 50, 60]],

       [[10, 20, 30],
        [ 5, 10, 20],
        [11, 22, 33],
        [44, 55, 66]]])

In [60]:
arr3d.shape

(2, 4, 3)

In [64]:
arr2d = arr3d.reshape(2,12)
arr2d

array([[ 1,  2,  3,  4,  5,  6, 10, 25, 35, 40, 50, 60],
       [10, 20, 30,  5, 10, 20, 11, 22, 33, 44, 55, 66]])

In [65]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [66]:
arr2d = arr.reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [67]:
arr3d = np.arange(30).reshape(2,3,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [68]:
# Bilinmeyet Boyut !
# .reshape() methodu kullanılırken hesaplamak istemediğimiz boyut yerine -1 yazıp otomatik hesaplattırabiliriz.

In [69]:
arr3d = np.arange(120).reshape(5,2,-1)
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

In [ ]:
# 0-59(59 dahil toplam 60 sayı) arasındaki tam sayılardan oluşan bir array oluşturun. 
# Ardından bu array'in shape'ini değiştirerek istediğiniz shape'lerde 3 boyutlu bir array elde edin. Daha sonrasında boyutuna ve shapeine bakın.

In [71]:
arr = np.arange(60).reshape(2,-1,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [72]:
arr.ndim

3

In [73]:
arr.shape

(2, 6, 5)

# Arrayleri Düzleştirme(Flatten)

In [ ]:
# Düzleştirme işlemi(Flatten) çok boyutlu bir array'i 1 boyutlu hale döndürmeye denir.
# Basitçe .reshape(-1) metoduyla yapılır.

In [74]:
arr2d = np.arange(40).reshape(8,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [75]:
arr2d.shape

(8, 5)

In [77]:
arr = arr2d.reshape(-1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [78]:
arr3d = np.arange(60).reshape(-1,5,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [82]:
arr3d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
# Soru : 30 elemanlı ve 3 boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve boyutunu, shapeini kontrol edin.

In [83]:
arr3d = np.random.randint(1,100,30).reshape(2,-1,3)
arr3d

array([[[97, 74, 54],
        [86, 28, 25],
        [ 4, 22, 66],
        [50, 88, 95],
        [47, 67, 11]],

       [[17,  2, 18],
        [ 8, 28, 20],
        [39,  4, 84],
        [56, 29, 98],
        [93, 84, 26]]])

In [84]:
arr3d.reshape(-1)

array([97, 74, 54, 86, 28, 25,  4, 22, 66, 50, 88, 95, 47, 67, 11, 17,  2,
       18,  8, 28, 20, 39,  4, 84, 56, 29, 98, 93, 84, 26])

# Çok Boyutlu Arraylerde Iteration(Yineleme)

In [85]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
for x in arr1d:
  print(x)

0
1
2
3
4
5
6
7
8
9


In [89]:
arr2d = np.arange(20).reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [90]:
for x in arr2d:
  print(x)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [91]:
for x in arr2d:
  for y in x:
    print(y)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [92]:
arr3d = np.arange(30).reshape(-1,3,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [93]:
for x in arr3d:
  for y in x:
    for z in y:
      print(z)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


# Çok Boyutlu Arraylerde nditer() Kullanımı

In [94]:
# For döngüsü arrayin boyutu kadar sayıda kullanılırsa ancak array'in bütün elemanlarına tek tek erişebiliriz.
# Çok boyutlu arraylerde nditer() fonksiyonu bunun için geliştirilmiştir.
# For döngüsüne çok daha efektif ve hızlı bir şekilde tüm elemanları dönmenizi sağlar.

In [95]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [97]:
for x in np.nditer(arr3d):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [ ]:
# Soru : 0'dan 119'a kadar(119 dahil) toplamda 120 elemanlı bir array oluşturun. Ardından bu array'in shape'ini ayarlayarak 3 boyutlu hale getirin. 
# Devamında da içindeki bütün elemanları tek tek dönün.

In [98]:
arr3d = np.arange(120).reshape(2,-1,5)
arr3d

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74],
        [ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119]]])

In [99]:
for x in np.nditer(arr3d):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119


# Array Elemanları Arasında 4 İşlem

In [116]:
arr1 = np.array([10,20,50,100])
arr2 = np.array([5,7,9,4])

In [101]:
arr1

array([ 10,  20,  50, 100])

In [102]:
arr2

array([ 5,  7,  9, -1])

In [117]:
arr1 + arr2

array([ 15,  27,  59, 104])

In [104]:
arr1.__add__(arr2)

array([15, 27, 59, 99])

In [105]:
arr1 - arr2

array([  5,  13,  41, 101])

In [106]:
arr1.__sub__(arr2)

array([  5,  13,  41, 101])

In [107]:
arr1 * arr2

array([  50,  140,  450, -100])

In [110]:
arr1 ** arr2

array([          100000,       1280000000, 1953125000000000,
              100000000])

In [111]:
arr1 / arr2 

array([ 2.        ,  2.85714286,  5.55555556, 25.        ])

In [112]:
arr1 // arr2

array([ 2,  2,  5, 25])

# Bir Arrayin Toplamına/Ortalamasına/Varyansına/Standart Sapmasına Bakma

In [113]:
arr = np.random.randint(0,10, 10)
arr

array([0, 2, 9, 5, 5, 6, 9, 0, 2, 0])

In [118]:
arr.sum()

38

In [119]:
arr.mean()

3.8

In [123]:
arr.var()

11.16

In [121]:
arr.std()

3.340658617698013

In [124]:
arr

array([0, 2, 9, 5, 5, 6, 9, 0, 2, 0])

In [125]:
np.sqrt(arr)

array([0.        , 1.41421356, 3.        , 2.23606798, 2.23606798,
       2.44948974, 3.        , 0.        , 1.41421356, 0.        ])

In [126]:
np.sin(arr)

array([ 0.        ,  0.90929743,  0.41211849, -0.95892427, -0.95892427,
       -0.2794155 ,  0.41211849,  0.        ,  0.90929743,  0.        ])

In [ ]:
# Soru : 0-100(100 dahil) arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.

In [127]:
arr = np.random.randint(0,101 , 10)
print(arr.sum())
print(arr.mean())
print(arr.var())
print(arr.std())

507
50.7
783.2099999999999
27.98588930157482


# NumPy Arraylerini Birleştirme (Concatenate)

In [ ]:
# Numpy Arraylerini birleştirme işlemi .concatenate() fonksiyonu ile yapılır. Fonksiyonun içine liste halinde birleştirilecek arrayler verilir.
# np.concatenate([arr1,arr2] , axis = 1)

In [128]:
arr1 = np.array([10,20,30,70])
arr2 = np.array([100,200,600,900])

In [129]:
arr1

array([10, 20, 30, 70])

In [130]:
arr2

array([100, 200, 600, 900])

In [131]:
np.concatenate([arr1,arr2] , axis = 0 )

array([ 10,  20,  30,  70, 100, 200, 600, 900])

In [133]:
arr1 = np.array([[1,2,3] , [5,6,7]])
arr2 = np.array([[100,200,300] , [700,800,900]])

In [134]:
arr1

array([[1, 2, 3],
       [5, 6, 7]])

In [135]:
arr2

array([[100, 200, 300],
       [700, 800, 900]])

In [139]:
np.concatenate([arr1,arr2] , axis = 0)

array([[  1,   2,   3],
       [  5,   6,   7],
       [100, 200, 300],
       [700, 800, 900]])

In [137]:
np.concatenate([arr1,arr2] , axis = 1)

array([[  1,   2,   3, 100, 200, 300],
       [  5,   6,   7, 700, 800, 900]])

# Arrayleri Stackleme(Yığınlama) İşlemleri

In [140]:
# Concatenate işleminin hemen hemen aynısıdır tek farkı yeni bir boyut(eksen) üzerinde yığınlamalar yapmasıdır.

In [141]:
arr1

array([[1, 2, 3],
       [5, 6, 7]])

In [142]:
arr2

array([[100, 200, 300],
       [700, 800, 900]])

In [143]:
np.concatenate([arr1,arr2] , axis = 0)

array([[  1,   2,   3],
       [  5,   6,   7],
       [100, 200, 300],
       [700, 800, 900]])

In [144]:
np.stack([arr1,arr2] , axis = 0)

array([[[  1,   2,   3],
        [  5,   6,   7]],

       [[100, 200, 300],
        [700, 800, 900]]])

In [ ]:
# np.hstack() --> Satır boyunca yığınlama
# np.vstack() --> Sütun boyunca yığınlama

# NumPy Arraylerinde Arama

In [ ]:
# Aradığımız değerlerin bulunduğu indexleri döndürmek için np.where() fonksiyonunu kullanarız.
# np.where() içerisine argüman olarak condition(şart) alır.

In [146]:
arr = np.array([1,2,5,6,7,7,9,2,2,2])
arr

array([1, 2, 5, 6, 7, 7, 9, 2, 2, 2])

In [147]:
np.where(arr == 9) # Arrayimizin kaçıncı indeksindeki elemanlar 9'dur ?

(array([6]),)

In [148]:
np.where(arr == 2)

(array([1, 7, 8, 9]),)

In [149]:
np.where(arr%2 != 0 ) # Tek elemanların indeksleri

(array([0, 2, 4, 5, 6]),)

# NumPy'da Random Kütüphanesi

In [150]:
# Random diye ayrı bir kütüphane olmasının yanı sıra NumPy kütüphanesinin içinde random adında bir modül de bulunur.
# NumPy'ın içindeki random modülü normal random kütüphanesinden daha kapsamlıdır.

In [151]:
# from numpy import random as rd
import numpy as np

In [153]:
np.random.rand() # 0-1 arası 1 tane sayı döndürür

0.057728439229184136

In [154]:
np.random.randn(5) # Normal dağılımdan random 5 tane veri çek

array([ 0.27138892, -0.78894347, -1.65346792,  0.38273185,  2.75811026])

In [155]:
np.random.randint(low = 10 , high = 30 , size = 5)

array([17, 23, 22, 13, 20])

In [156]:
np.random.randint(10 , 30 , 5)

array([20, 29, 19, 13, 19])

In [157]:
arr

array([1, 2, 5, 6, 7, 7, 9, 2, 2, 2])

In [160]:
np.random.choice(arr)

5

In [163]:
np.random.choice([3,-1,15])

15

In [ ]:
# Done.