# https://github.com/EmincanY

# NumPy Nedir ?

In [2]:
# NumPy açık kaynaklı kodlu ücretsiz ve özgür bir Python kütüphanesidir.
# NumPy --> Numerical Python anlamına gelir. Sayılarla daha hızlı matematik işlemler yapmamızı sağlar
# NumPy kütüphanesinin en temel elemanı array(dizi)'dir.
# Arrayleri Python dizilerinin çok boyutlu olanı gibi düşünebilirsiniz.
# Arrayler Listelerden yaklaşık 50 kat daha hızlı çalışır.
# NumPy arraylerinin hızlı çalışmasının sebebi bu kütüphanenin çok büyük oranda C ve C++ ile yazılmış olması.

# NumPy Yüklenmesi

In [3]:
# !pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# NumPy'ı projeye dahil etme

In [4]:
# import numpy
import numpy as np

# NumPy array'leri oluşturma

In [ ]:
# Arrayler çok boyutlu diziler gibi düşünebilir.
# Arraylerin boyutları(dimension) vardır. 0d , 1d , 2d ,3d ,4d ....

# Arrayleri oluşturmanın 3 farklı yolu vardır.
# 1) Liste ya da tuple benzeri nesneleri array'e döndürebiliriz.                 np.array([1,2,3])
# 2) Built-in hazır fonksiyonlar yardımıyla arrayler oluşturabiliriz.            np.arange() , np.linspace() , np.logspace() vb.
# 3) Rastgele data üreterek                                                      np.random modülünün içindeki fonksiyonlar yardımıyla.

In [7]:
arr0d = np.array(53)
arr0d

array(53)

In [8]:
arr1d = np.array([1,2,3,4])
arr1d

array([1, 2, 3, 4])

In [9]:
arr2d = np.array([[1,2,3] , [4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr3d = np.array([[[1,2,3] , [4,5,6]] , [[7,8,9] , [100,200,300]]])
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [15]:
# Soru : İstediğiniz elemanlardan oluşan 2d bir array oluşturun

# Built-in Functionlarla Hızlıca NumPy Arrayleri Oluşturma

In [ ]:
# np.arange() fonksiyonu ile hızlıca arrayler oluşturabiliriz. İstediğimiz sayı aralığında ardışık artan arrayler oluştururuz.
# Kullanımı aynen range() gibi. Start point dahil, End point dahil değil.
# Gene aynı range() fonksiyonunda olduğu gibi (start-stop-step parametrelerini alır.)

In [18]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(30,101,2)

array([ 30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
        56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,
        82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
# np.linspace() fonksiyonuyla da hızlıca arrayler oluşturulabilir.

In [26]:
np.linspace(30,50,6 , dtype=int) # Endpoint bunda dahil.

array([30, 34, 38, 42, 46, 50])

In [25]:
np.logspace(1,3 , 5) # 10**1 ile 10**3 arasında logaritmik artış yapan 5 tane veriden oluşan bir array oluştur.

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [ ]:
# Soru : 10,15,20,25....100 şeklindeki arrayi oluşturunuz.

In [27]:
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [ ]:
# Soru : 0-1000 arasında eşit aralıklarla ilerleyen 26 tane sayı oluşturun.

In [28]:
np.linspace(0,1000,26)

array([   0.,   40.,   80.,  120.,  160.,  200.,  240.,  280.,  320.,
        360.,  400.,  440.,  480.,  520.,  560.,  600.,  640.,  680.,
        720.,  760.,  800.,  840.,  880.,  920.,  960., 1000.])

In [30]:
np.zeros(5 , dtype= 'int')

array([0, 0, 0, 0, 0])

In [32]:
np.zeros((2,3) , dtype= int)

array([[0, 0, 0],
       [0, 0, 0]])

In [34]:
np.ones(10 , dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [35]:
np.ones((3,5) , dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
np.ones((2,3,5) , dtype = int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [38]:
np.eye(5 , dtype = 'int') # 5x5 birim matris

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
# Soru : Sadece 0 değerlerinden oluşan (2,6) formatında array oluşturun.

In [39]:
np.zeros((2,6) , dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [40]:
# np.random modülünü kullanarak rastgele verilerle arrayler oluşturmak

In [41]:
np.random.rand(3) # 3 tane 0-1 aralığında değerden oluşan bir array oluşturur.

array([0.34925949, 0.80368685, 0.79119433])

In [45]:
np.random.rand(2,5)

array([[0.73712704, 0.85467983, 0.55584668, 0.18983823, 0.08293358],
       [0.76572522, 0.28385987, 0.48880215, 0.97040128, 0.90842668]])

In [47]:
np.random.rand(3) * 10 # 3 tane 0-10 aralığında değerden oluşan bir array oluşturdu.

array([9.18557463, 3.6752947 , 5.00442262])

In [48]:
np.random.randint(15,50,5)

array([33, 20, 31, 40, 26])

In [49]:
np.random.randint(0,100, (3,6))

array([[70, 88, 21, 68, 12, 62],
       [36, 92, 38, 63, 17, 11],
       [27, 34, 67, 18, 33, 23]])

In [ ]:
# Soru : 0-50 arasında rastgele tam sayılardan oluşan 4-6 formatında 24 tane tam sayıdan oluşan bir array oluşturun.

In [50]:
np.random.randint(0,50, (4,6))

array([[ 0, 26,  5, 43, 29,  0],
       [13, 18, 17, 36, 17, 22],
       [34, 17, 47, 40, 32, 30],
       [ 5, 18,  7, 31, 49, 34]])

# Arrayin Boyut Sayısını ve Shape'ini Kontrol Etmek

In [51]:
arr0d

array(53)

In [52]:
arr1d

array([1, 2, 3, 4])

In [53]:
arr2d

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300],
       [ 50,  60,  80],
       [ 10,  20,  25]])

In [54]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [ ]:
# .ndim attribute'ı ile arrayimizin kaç boyutlu olduğuna bakabiliriz.

In [55]:
arr0d.ndim

0

In [56]:
arr1d.ndim

1

In [57]:
arr2d.ndim

2

In [58]:
arr3d.ndim

3

In [60]:
arr2d

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300],
       [ 50,  60,  80],
       [ 10,  20,  25]])

In [61]:
# .shape attribute'ı ile arrayin shapeine bakılabilir

In [62]:
arr2d.shape

(5, 3)

In [63]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [64]:
arr3d.shape

(2, 2, 3)

# NumPy Arraylerini İndeksleme ve Öğelerime Erişme

In [65]:
arr1d # 1 boyutlu arrayler aynı listeler gibi düşünülebilir.

array([1, 2, 3, 4])

In [67]:
arr1d[3]

4

In [68]:
arr2d

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300],
       [ 50,  60,  80],
       [ 10,  20,  25]])

In [71]:
arr2d[3][2] # arr2d[3,2]

80

In [72]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [73]:
arr3d[0][1][2] # arr3d[0,1,2]

6

In [74]:
arr3d[1][0][-1] # Negatif indexleme burda da var.

9

In [ ]:
# Soru : 53'den 61'e kadar(53 ve 61 dahil) olan tam sayıları içeren bir boyutlu bir array oluşturun. Ardından bu array'in 4.indexindeki sayıyı ekrana bastırın.

In [79]:
arr = np.arange(53,62)
arr[4]

57

# NumPy Dizilerinin Maximum-Minimum Elemanlarına ve bu Elemanların İndexlerine Erişme

In [80]:
arr = np.random.randint(1,100,10)
arr

array([54, 20, 67, 30, 76, 80, 89,  6, 35,  4])

In [81]:
arr.max()

89

In [82]:
arr.argmax()

6

In [83]:
arr.min()

4

In [84]:
arr.argmin()

9

# NumPy Arraylerinde Slicing(Dilimleme) Yapılabilir

In [86]:
arr = np.arange(50,65)
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [88]:
arr[5:11]

array([55, 56, 57, 58, 59, 60])

In [92]:
arr[-5:]

array([60, 61, 62, 63, 64])

In [93]:
arr[2:10:2]

array([52, 54, 56, 58])

In [94]:
arr[5:11] = 999 # Broadcasting

In [95]:
arr

array([ 50,  51,  52,  53,  54, 999, 999, 999, 999, 999, 999,  61,  62,
        63,  64])

In [ ]:
# Soru
# -30 ile 10(İkisi de dahil) arasındaki tam sayılardan bir array oluşturun. Ardından slicing yaparak 5. ve 18. indexler arasındaki sayılardan(ikisi de dahil) oluşan bir array oluşturun.

In [100]:
arr = np.arange(-30 , 11)
arr[5:19]

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12])

# Bir Arrayin Veri Türünü(Data Type'ını) Kontrol Etme

In [ ]:
# .dtype attribute'ı ile arrayimizin data type'ı kontrol edilebilir.

In [101]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
arr.dtype

dtype('int64')

In [105]:
arr2 = np.arange(100, dtype = 'float')
arr2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [106]:
arr2.dtype

dtype('float64')

In [107]:
arr3 = np.array(['a','b','c'])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [108]:
arr3.dtype

dtype('<U1')

# Bir Arrayin Dtype'ını Değiştirme

In [109]:
arr = np.array([1.2 , 3.5 , 5.8])
arr

array([1.2, 3.5, 5.8])

In [111]:
arr.dtype

dtype('float64')

In [ ]:
# .astype() methodu ile arraylerin dtype'ı değiştirebilir.

In [114]:
arr = arr.astype('int')
arr

array([ 5,  7, 19,  1, 22, 99,  4])

In [ ]:
# Soru :
# arr = np.array(['5', '7', '19', '1', '22', '99', '4']) şeklindeki array'in type'ını int'e döndürün ardından dtype'ını kontrol edin.

In [117]:
arr = np.array(['5', '7', '19', '1', '22', '99', '4'])

In [118]:
arr

array(['5', '7', '19', '1', '22', '99', '4'], dtype='<U2')

In [121]:
arr = arr.astype(int)

In [122]:
arr

array([ 5,  7, 19,  1, 22, 99,  4])

In [ ]:
# 1.Ders Sonu