In [1]:
import numpy as np

1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.

In [3]:
np.arange(30).reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [5]:
arr = np.random.randint(0,1000 , 60).reshape(5,2,6)
print(arr)

print(arr.shape)
print(arr.ndim)

[[[399 944 123 723 367 225]
  [613 747 327 538 557 359]]

 [[208 370  90 911 343  51]
  [518 738 682 340 965 325]]

 [[294 137 785 384 857 790]
  [137 498 682 659  90 543]]

 [[240 136 325 625 114  93]
  [416 465 980 100 895 303]]

 [[986 401 385 455 517 271]
  [787 577 520 988 617 342]]]
(5, 2, 6)
3


3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [6]:
arr = np.random.randint(0,10 , 20).reshape(5,4)
arr.reshape(-1) # Flatten

array([4, 0, 2, 1, 1, 0, 3, 5, 6, 4, 7, 2, 2, 5, 1, 6, 3, 3, 7, 2])

4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.

In [8]:
arr2d = np.arange(20).reshape(10,2)
for x in arr2d :
    for y in x : 
        print(y)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [10]:
for x in np.nditer(arr2d):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.

In [12]:
arr1 = np.arange(5,31 , 5)
arr2 = np.arange(1,7)
print(arr1)
print(arr2)
print("\n\n\n")

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 5 10 15 20 25 30]
[1 2 3 4 5 6]




[ 6 12 18 24 30 36]
[ 4  8 12 16 20 24]
[  5  20  45  80 125 180]
[5. 5. 5. 5. 5. 5.]


6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.

In [13]:
arr = np.random.randint(0,100 , 10)
print(arr)
print("\n\n\n")

print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.var())
print(arr.std())

[95 34 33 29 11 23 66 80  6 70]




447
44.7
95
847.21
29.106872040808508


7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.

In [17]:
arr1 = np.arange(20)
arr2 = np.arange(500, 531)
np.concatenate([arr1,arr2] , axis = 0)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.

In [18]:
arr1 = np.arange(15,51)
arr2 = np.arange(10,101)
arr3 = np.concatenate([arr1,arr2] , axis = 0)
arr3[25:51] = 888 # Broadcasting
print(arr3)

[ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32
  33  34  35  36  37  38  39 888 888 888 888 888 888 888 888 888 888 888
 888 888 888 888 888 888 888 888 888 888 888 888 888 888 888  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.

In [23]:
arr1 = np.arange(40).reshape(8,5)
arr2 = np.arange(320, 360).reshape(8,5)
print(arr1)
print(arr2)
print("\n\n")
print(np.concatenate([arr1,arr2] , axis = 0))
print("\n\n")
print(np.concatenate([arr1,arr2] , axis = 1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[[320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]



[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]



[[  0   1   2   3   4 320 321 322 323 324]
 [  5   6   7   8   9 325 326 327 328 329]
 [ 10  11  12  13  14 330 331 332 333 334]
 [ 15  16  17  18  19 335 336 337 338 339]
 [ 20  21  22  23  24 340 341 342 343 344]
 [ 25  26  27  28  29 345 346 347 348 349]
 [ 30  31  32  33  34 350 351 352 353

10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.

In [24]:
print(np.concatenate([arr1,arr2] , axis = 2))

AxisError: axis 2 is out of bounds for array of dimension 2

In [25]:
np.stack([arr1 , arr2] , axis = 2)

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.

In [26]:
arr = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(arr == 5)

(array([ 5, 13], dtype=int64),)

12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.

In [27]:
np.where(arr % 2 == 0)

(array([ 1,  3,  4,  6,  7,  9, 11], dtype=int64),)

13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.

In [28]:
np.where(arr > 4)

(array([ 1,  2,  5,  9, 10, 11, 13], dtype=int64),)

14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.

In [29]:
np.where(arr % 5 == 0)

(array([ 1,  2,  5, 13], dtype=int64),)

15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin

In [31]:
np.random.randint(85,101)

98

16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.

In [32]:
np.random.randint(10,100 , size = (3,3))

array([[12, 13, 14],
       [85, 13, 30],
       [92, 73, 40]])

17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.

In [37]:
arr = np.arange(35,60)
np.random.choice(arr)

48

18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [38]:
np.random.choice([3, 8 , 10 , 53] , size = (2,5)) 

array([[ 3, 10, 53, 53,  3],
       [ 3, 10, 10,  3,  8]])

In [ ]:
# Done.